### PR TITLE
vulkan_wrapper enhancements

### PR DESCRIPTION
**Pull request by AlessandroBorges**
Hi !
I'd like to submit an enhancement to vulkan_wrapper.
Basically, it replaces all Vulkan procedure loading with **dlsym** by a more specification friendly loading method with **vkGetInstanceProcAddr**. Exception is on vkGetInstanceProcAddr itself, which is the unique Vulkan function loaded with dlsym.

Once **vkGetInstanceProcAddr** is loaded, it can be used to load the following functions, passing instance parameter as nullptr : 
- vkEnumerateInstanceExtensionProperties
- vkEnumerateInstanceLayerProperties
-  vkCreateInstance

A live instance of VkInstance, necessary to load all core and enabled extension functions, will be available only after a call to **vkCreateInstance**.
So I proposed a Delegate vkCreateInstance, which will do a double job: 
(i) call the the real one function (keep by vkCreateInstance_HOOK) and (ii) call a function to load all remaining core and enabled extension functions.

**Reason**
Vulkan spec states the following, at Chapter 3:

> Vulkan commands are not necessarily exposed statically on a platform. Function pointers for all Vulkan commands can be obtained with the command: 
> 
> ```
>  PFN_vkVoidFunction vkGetInstanceProcAddr( 
>                    VkInstance instance,
>                    const char* pName);
> ```

With proposed fix, we attend the specification and avoid issues with Vulkan drivers which only exposes  **vkGetInstanceProcAddr** . 
Same apply to extension functions (the vk \* EXT and vk \* KHR functions). Those functions should be available only when enabled through VkInstanceCreateInfo.ppEnabledExtensionNames at VkInstance creation.

### CODE REVIEW

**Comment by AlessandroBorges** [comment]
I  signed the CLA.

**Comment by courtney-g** [comment]
It would be preferred to modify the code generator to generate what you want. That will help prevent issues with missing definitions in the future as Vulkan grows.

**Comment by AlessandroBorges** [comment]
I couldn't find the generators you guys used  to generate wrapper files.
For my developments I use pure Java for generators.

**Comment by ggfan** [comment]
Upstream owner created an issue tracking this:
  https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1697
it will get processed there, and once it is updated ( resolved ), will update it into this repo ( this repo is a copy-paste process from up-stream for wrapper ).

Thank you for your PR, it is great one.   Closing down this one for now.

**Pull request closed without merging**
